const assert=require('assert');const L=require('./logic.js');let n=0;const t=(name,fn)=>{fn();n++;console.log('PASS',name)};
t('states',()=>assert.deepStrictEqual(L.STATES,["NEW","WAITING","DUE","WON","LOST"]));
t('fixtures-five',()=>assert.strictEqual(L.cloneFixtures().length,5));
t('fixture-states',()=>assert.deepStrictEqual(L.cloneFixtures().map(x=>x.state),L.STATES));
t('move-new-waiting',()=>assert.strictEqual(L.move(L.cloneFixtures()[0],'WAITING','x').state,'WAITING'));
t('invalid-state',()=>assert.throws(()=>L.move(L.cloneFixtures()[0],'BOGUS','x'),/invalid_state/));
t('overdue-active',()=>assert.strictEqual(L.isOverdue({id:'x',label:'x',state:'WAITING',dueDate:'2026-09-20',notes:'',updatedAt:''},'2026-09-25'),true));
t('not-overdue-future',()=>assert.strictEqual(L.isOverdue({id:'x',label:'x',state:'DUE',dueDate:'2026-09-30',notes:'',updatedAt:''},'2026-09-25'),false));
t('won-not-overdue',()=>assert.strictEqual(L.isOverdue({id:'x',label:'x',state:'WON',dueDate:'2026-01-01',notes:'',updatedAt:''},'2026-09-25'),false));
t('lost-not-overdue',()=>assert.strictEqual(L.isOverdue({id:'x',label:'x',state:'LOST',dueDate:'2026-01-01',notes:'',updatedAt:''},'2026-09-25'),false));
t('waiting-due-distinct',()=>assert.notStrictEqual('WAITING','DUE'));
t('csv-header',()=>assert.ok(L.toCSV(L.cloneFixtures(),'2026-09-25').startsWith('id,label,state,due_date,overdue,notes,updated_at\n')));
t('csv-deterministic',()=>assert.strictEqual(L.toCSV(L.cloneFixtures().reverse(),'2026-09-25'),L.toCSV(L.cloneFixtures(),'2026-09-25')));
t('csv-all-records',()=>assert.strictEqual(L.toCSV(L.cloneFixtures(),'2026-09-25').trim().split('\n').length,6));
t('csv-quote',()=>assert.ok(L.toCSV([{id:'a',label:'A, B',state:'NEW',dueDate:'',notes:'say "hi"',updatedAt:''}],'2026-09-25').includes('"A, B"')));
t('normalize-state-case',()=>assert.strictEqual(L.normalizeRecord({id:'a',label:'b',state:'new'}).state,'NEW'));
t('missing-id',()=>assert.throws(()=>L.normalizeRecord({label:'b',state:'NEW'}),/id_and_label_required/));
t('missing-label',()=>assert.throws(()=>L.normalizeRecord({id:'a',state:'NEW'}),/id_and_label_required/));
t('bad-date',()=>assert.throws(()=>L.normalizeRecord({id:'a',label:'b',state:'NEW',dueDate:'09/25/26'}),/invalid_due_date/));
t('counts',()=>assert.deepStrictEqual(L.boardCounts(L.cloneFixtures()),{NEW:1,WAITING:1,DUE:1,WON:1,LOST:1}));
t('fixture-clone',()=>{const a=L.cloneFixtures();a[0].label='changed';assert.notStrictEqual(a[0].label,L.cloneFixtures()[0].label)});
console.log('TOTAL_PASS',n);